; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico2040]
;platform = raspberrypi
;board = pico
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico

board_build.core = earlephilhower
build_flags =
    -D PIN_MPU_INTERRUPT=3
    -D PIN_LED_STRIP_1=12
    -D PIN_LED_STRIP_2=13
    -D PIN_BUTTON_MULTI=23
    -D PIN_BATTERY_ADC=29
    -D PIN_USB_SENSE=24
    -D PIN_RM2_WL_ON=17
    -D PIN_RM2_BL_ON=17
    -D PIN_RM2_WL_CS=18
    -D PIN_RM2_WL_CLK=19
    -D PIN_RM2_WL_DATA=20
    -D PIN_RM2_WL_WAKE=20
    -D NIGHTKITE_BLE=0
    -D NIGHTKITE_RM2=0
    -D NIGHTKITE_BOOT_DEBUG=1
    -D NIGHTKITE_SAFE_BOOT=0
    -D NIGHTKITE_HARDWARE=\"pico2040\"

lib_deps =
    https://github.com/electroniccats/mpu6050.git#b782cd06c5fb3b71d1de07d5e452dc8e04230c3e
    https://github.com/FastLED/FastLED.git#3d1f9fe373b295254354f6266030557a497594cf
    https://github.com/LennartHennigs/SimpleFSM.git#2e306c21dad93e48f242b776d6e0fb9ce7c4fba6
    https://github.com/SpacehuhnTech/SimpleCLI.git#d38105a242d89b8c87953bc17f67c2fa11c27458
    https://github.com/avdwebLibraries/avdweb_Switch.git#4809b2b0df4cba6f4c2f3f3ca7ea0ba9dc673154
    https://github.com/MattFryer/Smoothed.git#c81877ddffde771d32dc8f991f622c7746d85894

[env:pico2350_rm2_ble]
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pimoroni_pico_plus_2

board_build.core = earlephilhower
build_flags =
    -D PIN_MPU_INTERRUPT=3
    -D PIN_LED_STRIP_1=12
    -D PIN_LED_STRIP_2=13
    -D PIN_BUTTON_MULTI=45
    -D PIN_BATTERY_ADC=43
    -D PIN_USB_SENSE=24
    -D PIN_RM2_WL_ON=17
    -D PIN_RM2_BL_ON=17
    -D PIN_RM2_WL_CS=18
    -D PIN_RM2_WL_CLK=19
    -D PIN_RM2_WL_DATA=20
    -D PIN_RM2_WL_WAKE=20
    -D NIGHTKITE_BLE=1
    -D NIGHTKITE_RM2=1
    -D NIGHTKITE_BOOT_DEBUG=1
    -D NIGHTKITE_SAFE_BOOT=0
    -D NIGHTKITE_HARDWARE=\"pico2350-rm2-ble\"
    -D PICO_CYW43_SUPPORTED=1
    -D CYW43_PIN_WL_DYNAMIC=1
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH

lib_deps =
    https://github.com/electroniccats/mpu6050.git#b782cd06c5fb3b71d1de07d5e452dc8e04230c3e
    https://github.com/FastLED/FastLED.git#3d1f9fe373b295254354f6266030557a497594cf
    https://github.com/LennartHennigs/SimpleFSM.git#2e306c21dad93e48f242b776d6e0fb9ce7c4fba6
    https://github.com/SpacehuhnTech/SimpleCLI.git#d38105a242d89b8c87953bc17f67c2fa11c27458
    https://github.com/avdwebLibraries/avdweb_Switch.git#4809b2b0df4cba6f4c2f3f3ca7ea0ba9dc673154
    https://github.com/MattFryer/Smoothed.git#c81877ddffde771d32dc8f991f622c7746d85894

[env:pico2350]
;platform = raspberrypi
;board = pico
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pimoroni_pico_plus_2

board_build.core = earlephilhower
build_flags =
    -D PIN_MPU_INTERRUPT=3
    -D PIN_LED_STRIP_1=12
    -D PIN_LED_STRIP_2=13
    -D PIN_BUTTON_MULTI=45
    -D PIN_BATTERY_ADC=43
    -D PIN_USB_SENSE=24
    -D PIN_RM2_WL_ON=17
    -D PIN_RM2_BL_ON=17
    -D PIN_RM2_WL_CS=18
    -D PIN_RM2_WL_CLK=19
    -D PIN_RM2_WL_DATA=20
    -D PIN_RM2_WL_WAKE=20
    -D NIGHTKITE_BLE=0
    -D NIGHTKITE_RM2=0
    -D NIGHTKITE_BOOT_DEBUG=1
    -D NIGHTKITE_SAFE_BOOT=0
    -D NIGHTKITE_HARDWARE=\"pico2350\"

lib_deps =
    https://github.com/electroniccats/mpu6050.git#b782cd06c5fb3b71d1de07d5e452dc8e04230c3e
    https://github.com/FastLED/FastLED.git#3d1f9fe373b295254354f6266030557a497594cf
    https://github.com/LennartHennigs/SimpleFSM.git#2e306c21dad93e48f242b776d6e0fb9ce7c4fba6
    https://github.com/SpacehuhnTech/SimpleCLI.git#d38105a242d89b8c87953bc17f67c2fa11c27458
    https://github.com/avdwebLibraries/avdweb_Switch.git#4809b2b0df4cba6f4c2f3f3ca7ea0ba9dc673154
    https://github.com/MattFryer/Smoothed.git#c81877ddffde771d32dc8f991f622c7746d85894
