; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico2040]
;platform = raspberrypi
;board = pico
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico

board_build.core = earlephilhower
build_flags =
    -D PIN_MPU_INTERRUPT=3
    -D PIN_LED_STRIP_1=12
    -D PIN_LED_STRIP_2=13
    -D PIN_BUTTON_MULTI=23
    -D PIN_BATTERY_ADC=29
    -D PIN_USB_SENSE=24
    -D PIN_RM2_WL_ON=17
    -D PIN_RM2_BL_ON=17
    -D PIN_RM2_WL_CS=18
    -D PIN_RM2_WL_CLK=19
    -D PIN_RM2_WL_DATA=20
    -D PIN_RM2_WL_WAKE=20
    -D NIGHTKITE_BLE=0
    -D NIGHTKITE_RM2=0
    -D NIGHTKITE_BOOT_DEBUG=1
    -D NIGHTKITE_SAFE_BOOT=0
    -D NIGHTKITE_HARDWARE=\"pico2040\"

lib_deps =
    https://github.com/electroniccats/mpu6050
    https://github.com/FastLED/FastLED.git#3.10.2
    https://github.com/LennartHennigs/SimpleFSM
    https://github.com/SpacehuhnTech/SimpleCLI
    https://github.com/avdwebLibraries/avdweb_Switch
    https://github.com/MattFryer/Smoothed

[env:pico2350]
;platform = raspberrypi
;board = pico
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pimoroni_pico_plus_2

board_build.core = earlephilhower
build_flags =
    -D PIN_MPU_INTERRUPT=3
    -D PIN_LED_STRIP_1=12
    -D PIN_LED_STRIP_2=13
    -D PIN_BUTTON_MULTI=45
    -D PIN_BATTERY_ADC=43
    -D PIN_USB_SENSE=24
    -D PIN_RM2_WL_ON=17
    -D PIN_RM2_BL_ON=17
    -D PIN_RM2_WL_CS=18
    -D PIN_RM2_WL_CLK=19
    -D PIN_RM2_WL_DATA=20
    -D PIN_RM2_WL_WAKE=20
    -D NIGHTKITE_BLE=0
    -D NIGHTKITE_RM2=0
    -D NIGHTKITE_BOOT_DEBUG=1
    -D NIGHTKITE_SAFE_BOOT=0
    -D NIGHTKITE_HARDWARE=\"pico2350\"

lib_deps =
    https://github.com/electroniccats/mpu6050
    https://github.com/FastLED/FastLED.git#3.10.2
    https://github.com/LennartHennigs/SimpleFSM
    https://github.com/SpacehuhnTech/SimpleCLI
    https://github.com/avdwebLibraries/avdweb_Switch
    https://github.com/MattFryer/Smoothed
